// Differential tokenizer test: compares the C++ tokenize pipeline (official
// clean-chain port + BPE) against the OFFICIAL Python SimpleTokenizer output
// generated by tests/diff_tokenizer_corpus.py.
//
//   ./diff_tokenizer <model.gguf> <corpus-dir>
//
// corpus-dir holds corpus.txt (base64 UTF-8 strings, one per line) and
// expected.txt (32 token ids per line, produced by the official tokenizer).
#include "sam3.h"

#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

static bool read_lines(const std::string& path, std::vector<std::string>& lines) {
    std::ifstream f(path);
    if (!f) return false;
    std::string line;
    while (std::getline(f, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        lines.push_back(line);
    }
    return true;
}

static bool b64_decode(const std::string& in, std::string& out) {
    auto val = [](char c) -> int {
        if (c >= 'A' && c <= 'Z') return c - 'A';
        if (c >= 'a' && c <= 'z') return c - 'a' + 26;
        if (c >= '0' && c <= '9') return c - '0' + 52;
        if (c == '+') return 62;
        if (c == '/') return 63;
        return -1;
    };
    out.clear();
    int buf = 0, bits = 0;
    for (char c : in) {
        if (c == '=') break;
        const int v = val(c);
        if (v < 0) return false;
        buf = (buf << 6) | v;
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            out += (char)((buf >> bits) & 0xFF);
        }
    }
    return true;
}

int main(int argc, char** argv) {
    if (argc < 3) {
        fprintf(stderr, "Usage: %s <model.gguf> <corpus-dir> [--text]\n", argv[0]);
        fprintf(stderr, "  --text  compare against expected_clean.txt (clean-layer expectations)\n");
        return 1;
    }
    if (!sam3_test_load_tokenizer(argv[1])) {
        fprintf(stderr, "ERROR: failed to load tokenizer from %s\n", argv[1]);
        return 1;
    }
    std::vector<std::string> corpus_lines, expected_lines;
    if (!read_lines(std::string(argv[2]) + "/corpus.txt", corpus_lines) ||
        !read_lines(std::string(argv[2]) + "/expected.txt", expected_lines) ||
        corpus_lines.size() != expected_lines.size()) {
        fprintf(stderr, "ERROR: corpus files missing or mismatched\n");
        return 1;
    }

    const bool diff_text = argc > 3 && std::string(argv[3]) == "--text";
    if (diff_text) {
        // clean-layer comparison: expectations produced by the official
        // tokenizer's _clean_lower (expected_clean.txt)
        std::vector<std::string> clean_lines;
        if (!read_lines(std::string(argv[2]) + "/expected_clean.txt", clean_lines) ||
            clean_lines.size() != corpus_lines.size()) {
            fprintf(stderr, "ERROR: expected_clean.txt missing or mismatched\n");
            return 1;
        }
        int tp = 0, tf = 0;
        for (size_t i = 0; i < corpus_lines.size(); ++i) {
            std::string text, want;
            if (!b64_decode(corpus_lines[i], text) || !b64_decode(clean_lines[i], want)) continue;
            const std::string got = sam3_test_clean_text(text);
            if (got == want) { ++tp; }
            else {
                ++tf;
                printf("TEXT-FAIL case %zu: in=\"%s\"\n  want=%s\n  got =%s\n",
                       i, text.c_str(), want.c_str(), got.c_str());
            }
        }
        printf("clean-layer differential: %d/%d passed\n", tp, tp + tf);
        return tf == 0 ? 0 : 1;
    }

    int pass = 0, fail = 0;
    for (size_t i = 0; i < corpus_lines.size(); ++i) {
        std::string text;
        if (!b64_decode(corpus_lines[i], text)) {
            fprintf(stderr, "case %zu: bad base64\n", i);
            ++fail;
            continue;
        }
        const std::vector<int32_t> got = sam3_test_tokenize(text);
        std::vector<int32_t> want;
        {
            std::istringstream ss(expected_lines[i]);
            int v;
            while (ss >> v) want.push_back(v);
        }
        bool ok = (got == want);
        if (ok) {
            ++pass;
        } else {
            ++fail;
            printf("FAIL case %zu: \"%s\"\n  want:", i, text.c_str());
            for (int v : want) printf(" %d", v);
            printf("\n  got: ");
            for (int v : got) printf(" %d", v);
            printf("\n");
        }
    }
    printf("tokenizer differential: %d/%d passed (%.1f%%)\n",
           pass, pass + fail, 100.0 * pass / (pass + fail));
    return fail == 0 ? 0 : 1;
}
