#!/usr/bin/env python3
"""Generate sam3_text_tables.h — exact character tables for the C++ tokenizer's
text-cleaning pipeline, aligned with the official tokenizer_ve.py chain:

    basic_clean       = ftfy.fix_text + html.unescape x2 + strip
    whitespace_clean  = regex \\s+ -> " " (Unicode whitespace), strip
    lower             = Python str.lower (full Unicode)

The tables are generated from the local Python/ftfy (the same libraries the
official tokenizer uses) so the C++ side is exact by construction:

  - html5 named entities          (html.entities.html5, ~2200 entries)
  - ftfy WIDTH_MAP / LIGATURES / CONTROL_CHARS  (ftfy.chardata)
  - C1 controls -> Windows-1252   (ftfy fix_c1_controls semantics)
  - Unicode lowercase map         (str.lower, incl. multi-char results)
  - Unicode whitespace set        (str.isspace, for regex-module \\s)
  - NFC tables                    (unicodedata: NFD, CCC, composition)
  - mojibake suspicious-char set  (ftfy.badness categories, gate for
                                   fix_encoding attempts)

Regenerate after touching any of the source tables:
    python3 scripts/gen_text_tables.py
"""
import html.entities
import sys
import unicodedata

import ftfy.badness
from ftfy.chardata import WIDTH_MAP, LIGATURES, CONTROL_CHARS, HTML_ENTITIES


def utf8(cps):
    return "".join(chr(c) for c in cps)


def cstr(s):
    """C string literal for a UTF-8 string."""
    out = []
    for b in s.encode("utf-8"):
        c = chr(b)
        if c == '"':
            out.append('\\"')
        elif c == "\\":
            out.append("\\\\")
        elif 0x20 <= b < 0x7F:
            out.append(c)
        else:
            out.append("\\x%02x" % b)
    return '"' + "".join(out) + '"'


def cchar(cp):
    return cstr(chr(cp))


L = []
w = L.append
w("/*")
w("** sam3_text_tables.h — GENERATED by scripts/gen_text_tables.py.")
w("** Do not edit by hand; regenerate with `python3 scripts/gen_text_tables.py`.")
w("** Source of truth: Python stdlib (html, unicodedata) + ftfy %s." % getattr(__import__("ftfy"), "__version__", "?"))
w("** Aligned with the official tokenizer_ve.py clean chain (ftfy + html.unescape).")
w("*/")
w("#ifndef SAM3_TEXT_TABLES_H")
w("#define SAM3_TEXT_TABLES_H")
w("")
w("namespace sam3_text_tables {")
w("")

# ── 1. HTML5 named entities ────────────────────────────────────────────────
ents = sorted(html.entities.html5.items())  # name (with/without ';') -> text
w("// html.entities.html5: name -> replacement text (sorted by name for binary search)")
w("struct sam3_html5_ent { const char* name; const char* text; };")
w("inline const sam3_html5_ent HTML5_ENTITIES[%d] = {" % len(ents))
for name, text in ents:
    w("    {%s, %s}," % (cstr(name), cstr(text)))
w("};")
w("inline const int NUM_HTML5_ENTITIES = %d;" % len(ents))
w("")

# ftfy HTML_ENTITIES: semicolon-only names + unambiguous ALL-CAPS variants
# (used by ftfy's own unescape_html fixer, step 1 of fix_text)
fe = sorted(HTML_ENTITIES.items())
w("// ftfy HTML_ENTITIES (semicolon-required names + unambiguous upper-case variants)")
w("inline const sam3_html5_ent FTFY_ENTITIES[%d] = {" % len(fe))
for name, text in fe:
    w("    {%s, %s}," % (cstr(name), cstr(text)))
w("};")
w("inline const int NUM_FTFY_ENTITIES = %d;" % len(fe))
w("")

# ── 2. ftfy translate tables ──────────────────────────────────────────────
w("// ftfy WIDTH_MAP: fullwidth/halfwidth normalization (char -> char, may be multi-char)")
wm = sorted(WIDTH_MAP.items())
w("struct sam3_char_map { uint32_t cp; const char* text; };")
w("inline const sam3_char_map WIDTH_MAP[%d] = {" % len(wm))
for cp, text in wm:
    w("    {0x%x, %s}," % (cp, cstr(text)))
w("};")
w("inline const int NUM_WIDTH_MAP = %d;" % len(wm))
w("")
lm = sorted(LIGATURES.items())
w("// ftfy LIGATURES: Latin ligature decomposition")
w("inline const sam3_char_map LIGATURES[%d] = {" % len(lm))
for cp, text in lm:
    w("    {0x%x, %s}," % (cp, cstr(text)))
w("};")
w("inline const int NUM_LIGATURES = %d;" % len(lm))
w("")
cc = sorted(CONTROL_CHARS.keys())
w("// ftfy CONTROL_CHARS: codepoints deleted by remove_control_chars")
w("inline const uint32_t CONTROL_CHARS[%d] = {" % len(cc))
for i in range(0, len(cc), 8):
    w("    " + " ".join("0x%x," % c for c in cc[i:i + 8]))
w("};")
w("inline const int NUM_CONTROL_CHARS = %d;" % len(cc))
w("")

# ── 3. C1 controls -> Windows-1252 (ftfy fix_c1_controls) ────────────────
w("// C1 control chars (U+0080..U+009F) -> their Windows-1252 interpretation.")
w("// None = the char maps to itself (sloppy pass-through).")
w("struct sam3_c1_map { uint32_t cp; const char* text; };")
c1 = []
for b in range(0x80, 0xA0):
    ch = chr(b)
    fixed = ch.encode("latin-1").decode("sloppy-windows-1252")
    if fixed != ch:
        c1.append((b, fixed))
w("inline const sam3_c1_map C1_MAP[%d] = {" % len(c1))
for cp, text in c1:
    w("    {0x%x, %s}," % (cp, cstr(text)))
w("};")
w("inline const int NUM_C1_MAP = %d;" % len(c1))
w("")

# ── 4. Unicode lowercase ──────────────────────────────────────────────────
w("// str.lower(): codepoints whose lowercase differs (multi-char results included)")
low = []
for cp in range(0x110000):
    if 0xD800 <= cp <= 0xDFFF:
        continue
    ch = chr(cp)
    lo = ch.lower()
    if lo != ch:
        low.append((cp, lo))
w("inline const sam3_char_map LOWER_MAP[%d] = {" % len(low))
for cp, text in low:
    w("    {0x%x, %s}," % (cp, cstr(text)))
w("};")
w("inline const int NUM_LOWER_MAP = %d;" % len(low))
w("")

# ── 5. Unicode whitespace (regex-module \s under re.UNICODE) ─────────────
ws = [cp for cp in range(0x110000)
      if not (0xD800 <= cp <= 0xDFFF) and chr(cp).isspace()]
w("// str.isspace() codepoints — what `regex` module \\s matches on str input")
w("inline const uint32_t UNICODE_WS[%d] = {" % len(ws))
for i in range(0, len(ws), 10):
    w("    " + " ".join("0x%x," % c for c in ws[i:i + 10]))
w("};")
w("inline const int NUM_UNICODE_WS = %d;" % len(ws))
w("")

# ── 6. NFC tables ─────────────────────────────────────────────────────────
# Canonical decomposition (excluding compatibility), CCC, primary composites.
nfd = []
ccc = []
for cp in range(0x110000):
    if 0xD800 <= cp <= 0xDFFF:
        continue
    ch = chr(cp)
    k = unicodedata.combining(ch)
    if k:
        ccc.append((cp, k))
    d = unicodedata.decomposition(ch)
    if d and not d.startswith("<"):
        seq = [int(x, 16) for x in d.split()]
        nfd.append((cp, seq))
nfd.sort()
w("// Canonical decomposition (unicodedata.decomposition, canonical only):")
w("// FLAT_NFD: flat codepoint array; NFD_IDX[i] = (cp, offset, len).")
flat = []
idx = []
for cp, seq in nfd:
    idx.append((cp, len(flat), len(seq)))
    flat.extend(seq)
w("struct sam3_nfd_idx { uint32_t cp; uint16_t off; uint16_t len; };")
w("inline const sam3_nfd_idx NFD_IDX[%d] = {" % len(idx))
for cp, off, ln in idx:
    w("    {0x%x, %d, %d}," % (cp, off, ln))
w("};")
w("inline const int NUM_NFD = %d;" % len(idx))
w("inline const uint32_t NFD_FLAT[%d] = {" % len(flat))
for i in range(0, len(flat), 8):
    w("    " + " ".join("0x%x," % c for c in flat[i:i + 8]))
w("};")
w("")
w("// Canonical combining classes (ccc != 0)")
w("struct sam3_ccc { uint32_t cp; uint8_t k; };")
w("inline const sam3_ccc CCC[%d] = {" % len(ccc))
for cp, k in ccc:
    w("    {0x%x, %d}," % (cp, k))
w("};")
w("inline const int NUM_CCC = %d;" % len(ccc))
w("")
# Primary composites: NFD is exactly 2 cps, first has ccc 0, not excluded.
excl = set()
for cp, seq in nfd:
    pass
comp = []
for cp, seq in nfd:
    if len(seq) == 2 and unicodedata.combining(chr(seq[0])) == 0:
        # composition exclusion: NFD(cp) of a non-starter pair, or singleton
        # decompositions; a pair is a primary composite iff
        # canonical_order(seq) recomposes per spec — the practical test used
        # here: NFC(seq) == chr(cp). unicodedata.normalize does the job.
        if unicodedata.normalize("NFC", utf8(seq)) == chr(cp):
            comp.append((seq[0], seq[1], cp))
comp.sort()
w("// Primary composites: (a, b) -> cp, sorted for binary search")
w("struct sam3_comp { uint32_t a, b, cp; };")
w("inline const sam3_comp COMPOSE[%d] = {" % len(comp))
for a, b, cp in comp:
    w("    {0x%x, 0x%x, 0x%x}," % (a, b, cp))
w("};")
w("inline const int NUM_COMPOSE = %d;" % len(comp))
w("")

# ── 7. Mojibake badness categories (ftfy.badness) ────────────────────────
w("// ftfy.badness MOJIBAKE_CATEGORIES, expanded (ranges resolved), sorted,")
w("// deduplicated. Used by the C++ port of BADNESS_RE (is_bad gate).")
from ftfy.badness import MOJIBAKE_CATEGORIES as _MC


def _expand_category(chars):
    out = []
    i = 0
    while i < len(chars):
        if i + 2 < len(chars) and chars[i + 1] == "-":
            out.extend(range(ord(chars[i]), ord(chars[i + 2]) + 1))
            i += 3
        else:
            out.append(ord(chars[i]))
            i += 1
    return sorted(set(out))


cat_names = list(_MC.keys())
w("struct sam3_cp_set { const uint32_t* cps; int n; };")
for name in cat_names:
    cps = _expand_category(_MC[name])
    var = name.upper()
    w("inline const uint32_t CAT_%s[%d] = {" % (var, len(cps)))
    for i in range(0, len(cps), 8):
        w("    " + " ".join("0x%x," % c for c in cps[i:i + 8]))
    w("};")
# index table in canonical order
w("enum { " + ", ".join("IDX_%s = %d" % (n.upper(), i) for i, n in enumerate(cat_names)) + " };")
w("inline const sam3_cp_set CATEGORIES[%d] = {" % len(cat_names))
for name in cat_names:
    cps = _expand_category(_MC[name])
    w("    { CAT_%s, %d }," % (name.upper(), len(cps)))
w("};")
w("inline const int NUM_CATEGORIES = %d;" % len(cat_names))
w("")

# union set (gate helper)
allbad = sorted(set().union(*[_expand_category(v) for v in _MC.values()]))
w("// union of all categories")
w("inline const uint32_t MOJIBAKE_CHARS[%d] = {" % len(allbad))
for i in range(0, len(allbad), 8):
    w("    " + " ".join("0x%x," % c for c in allbad[i:i + 8]))
w("};")
w("inline const int NUM_MOJIBAKE_CHARS = %d;" % len(allbad))
w("")

# ── 8. ftfy UTF8_CLUES (decode_inconsistent_utf8 detector) ──────────────
from ftfy.chardata import UTF8_CLUES


def _expand_clue(s):
    out = []
    i = 0
    while i < len(s):
        if i + 2 < len(s) and s[i + 1] == "-":
            out.extend(range(ord(s[i]), ord(s[i + 2]) + 1))
            i += 3
        else:
            out.append(ord(s[i]))
            i += 1
    return sorted(set(out))


for clue in ["utf8_first_of_2", "utf8_first_of_3", "utf8_first_of_4",
             "utf8_continuation", "utf8_continuation_strict"]:
    cps = _expand_clue(UTF8_CLUES[clue])
    var = clue.upper()
    w("inline const uint32_t %s[%d] = {" % (var, len(cps)))
    for i in range(0, len(cps), 8):
        w("    " + " ".join("0x%x," % c for c in cps[i:i + 8]))
    w("};")
    w("inline const int NUM_%s = %d;" % (var, len(cps)))
w("")

# ── 9. single-byte charmap codecs (ftfy CHARMAP_ENCODINGS) ─────────────
from ftfy.chardata import CHARMAP_ENCODINGS

w("// Single-byte codecs in official CHARMAP_ENCODINGS order; each table maps")
w("// encodable codepoints (bytes 0x80-0xFF decoded by the codec, plus U+FFFD ->")
w("// 0x1A for the sloppy codecs) to their byte. ASCII encodes identity-wise.")
for enc in CHARMAP_ENCODINGS:
    var = enc.upper().replace("-", "_")
    m = {}
    for b in range(0x80, 0x100):
        try:
            ch = bytes([b]).decode(enc)
        except UnicodeDecodeError:
            continue
        m.setdefault(ord(ch), b)
    if "sloppy" in enc:
        m.setdefault(0xFFFD, 0x1A)
    items = sorted(m.items())
    w("inline const uint32_t ENC_%s_CP[%d] = {" % (var, len(items)))
    for i in range(0, len(items), 8):
        w("    " + " ".join("0x%x," % cp for cp, _ in items[i:i + 8]))
    w("};")
    w("inline const uint8_t ENC_%s_BYTE[%d] = {" % (var, len(items)))
    for i in range(0, len(items), 16):
        w("    " + " ".join("0x%02x," % b for _, b in items[i:i + 16]))
    w("};")
    w("inline const int NUM_ENC_%s = %d;" % (var, len(items)))
w("struct sam3_codec { const uint32_t* cp; const uint8_t* byte; int n; };")
w("inline const sam3_codec CODECS[%d] = {" % len(CHARMAP_ENCODINGS))
for enc in CHARMAP_ENCODINGS:
    var = enc.upper().replace("-", "_")
    w("    { ENC_%s_CP, ENC_%s_BYTE, NUM_ENC_%s }," % (var, var, var))
w("};")
w("inline const int NUM_CODECS = %d;" % len(CHARMAP_ENCODINGS))
w("")

# ── 10. \p{L} / \p{N} ranges (CLIP pre-tokenizer classes) ────────────
w("// Unicode general-category L* (letters) and N* (numbers) as closed ranges,")
w("// sorted. Used by the CLIP pre-tokenizer ([\\p{L}]+, [\\p{N}], [^\\s\\p{L}\\p{N}]+).")


def _category_ranges(pred):
    cps = [cp for cp in range(0x110000)
           if not (0xD800 <= cp <= 0xDFFF) and pred(cp)]
    ranges = []
    for cp in cps:
        if ranges and cp == ranges[-1][1] + 1:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
    return ranges


LETTER_RANGES = _category_ranges(
    lambda cp: unicodedata.category(chr(cp)).startswith("L"))
NUMBER_RANGES = _category_ranges(
    lambda cp: unicodedata.category(chr(cp)).startswith("N"))

for name, ranges in [("LETTER", LETTER_RANGES), ("NUMBER", NUMBER_RANGES)]:
    w("struct sam3_cp_range { uint32_t lo, hi; };") if name == "LETTER" else None
    w("inline const sam3_cp_range %s_RANGES[%d] = {" % (name, len(ranges)))
    for i in range(0, len(ranges), 4):
        w("    " + " ".join("{0x%x,0x%x}," % (lo, hi) for lo, hi in ranges[i:i + 4]))
    w("};")
    w("inline const int NUM_%s_RANGES = %d;" % (name, len(ranges)))
w("")

w("} // namespace sam3_text_tables")
w("")
w("#endif // SAM3_TEXT_TABLES_H")

out = "\n".join(L) + "\n"
path = "sam3_text_tables.h"
with open(path, "w") as f:
    f.write(out)
print("wrote %s (%.1f KB, %d html5 ents, %d ftfy ents, %d width, %d lower, %d nfd, %d comp, %d mojibake chars)"
      % (path, len(out) / 1024.0, len(ents), len(fe), len(wm), len(low), len(idx), len(comp), len(allbad)))
